### ISSUE TITLE
Hardware - comparação com o modelo

### ISSUE THREAD

**Issue by meewmew** [camiladlr/Raspberry-P#1]

**Comment by Esumafoo** [comment]
Hardware Raspberry PI 5
[Hardware Raspberry Pi 5 (1).docx](https://github.com/user-attachments/files/17626516/Hardware.Raspberry.Pi.5.1.docx)

**Comment by Esumafoo** [comment]
Hardware Raspberry PI A (2013)
[Raspberry pi A.docx](https://github.com/user-attachments/files/17625288/Raspberry.pi.A.docx)
