### ISSUE TITLE
Apresentação com slides

### ISSUE THREAD

**Issue by meewmew** [camiladlr/Raspberry-P#13]

**Comment by Esumafoo** [comment]
@meewmew 
@barrosx7 
@Esumafoo 
https://docs.google.com/presentation/d/1SIMFYIx4ZXeDRADhLk-WvX3RBOVz8Vy2FQEWc_Grk0U/edit?usp=sharing

**Comment by meewmew** [comment]
@Esumafoo 
@barrosx7 
@meewmew 
https://docs.google.com/presentation/d/1SIMFYIx4ZXeDRADhLk-WvX3RBOVz8Vy2FQEWc_Grk0U/edit?pli=1#slide=id.g311edf2fbba_2_0
